### PR TITLE
Update trpo_agent.py

### PR DESCRIPTION
**Pull request by tigerneil**
fix `reduce` method missing in line 130.

### CODE REVIEW

**Comment by mjacar** [comment]
Is this a Python 2 vs Python 3 thing? I should note that I'm running this with Python 2 so I don't have this issue. I'm not sure how I want to handle the Python 2 vs Python 3 discrepancy. Do you have any thoughts?

**Comment by mjacar** [comment]
Maybe I'll open up a python3 branch and you can merge into that. What are your thoughts on that?

**Comment by tigerneil** [comment]
OK.

**Comment by mjacar** [comment]
So I made the python3 branch. I think you need to make a new PR to merge into that instead of master. I'll close this for now.

**Pull request closed without merging**
